### ISSUE TITLE
Nvidia 3090 +large*-gpu.cfg

### ISSUE THREAD

**Issue by MagiCsito** [polakowo/gpt2bot#19]
Hello,

I am trying to load the model "microsoft/DialoGPT-large" with the GPU nvidia 3090 but I receive this msg all the time:

RuntimeError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 24.00 GiB total capacity; 2.07 GiB already allocated; 0 bytes free; 2.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC
_CONF

I am trying to fix this error but I can't. Really I dont understand why if i have 24 GiB capacity, it only reserve 2.07 GiB for PyTorch.

Could you help me please?

PD: @MagiCsito in telegram.
----------------------------------

Update:
Monitoring resources, it go out of memory when it load "Human_vs_machine_wight" model (even with DialoGPT-small). Is there a way to can made this works with a nvidia 3090 (24 gb VRAM) and 64 RAM?

BTW, in colab works with 16 gb VRAM Graphic Card.

Thank you

**Comment by MagiCsito** [comment]
Solved! 
The problem was the compatibility of Cuda 11.7 with the instalation of pytorch stable cuda 11.6! So I removed pytorch with pip and installed the preview version and now, it is managing the VRAM correctly.
